# Generated by Django 6.0.7 on 2026-07-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='students/id_back/'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='students/id_front/'),
        ),
    ]
