# Generated by Django 6.0.7 on 2026-07-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSAAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
