# Generated by Django 6.0.7 on 2026-07-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_osaaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('has_violation', models.BooleanField(default=False)),
                ('violation_type', models.CharField(blank=True, max_length=100)),
                ('gate_opened', models.BooleanField(default=False)),
                ('entered', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Access Granted', max_length=50)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.accessattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('confirmed_entry', models.BooleanField(default=False)),
                ('sent_to_osa', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
