# Generated by Django 6.0.7 on 2026-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_accessattempt_entrylog_violationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessattempt',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
