# Generated by Django 6.0.7 on 2026-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_accessattempt_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
