# Generated by Django 6.0.7 on 2026-08-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_result', models.CharField(default='VIOLATION', max_length=20)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='ai_inspections/')),
                ('confirmation_status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed Violation'), ('REJECTED', 'False Detection')], default='PENDING', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_inspections', to='students.accessattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_inspections', to='students.student')),
            ],
        ),
    ]
