# Generated by Django 6.0.7 on 2026-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_aiinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinspection',
            name='recorded',
            field=models.BooleanField(default=False),
        ),
    ]
