# Generated by Django 6.0.7 on 2026-09-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_gate_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='students.aiinspection')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification', to='students.violationreport')),
            ],
        ),
    ]
