# Generated by Django 6.0.7 on 2026-09-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_violation_email_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_violations', to='students.aiinspection'),
        ),
        migrations.AddField(
            model_name='violationreport',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_reports', to='students.aiinspection'),
        ),
    ]
