# Generated by Django 6.0.7 on 2026-09-23 14:30

from django.db import migrations, models


def cancel_unsent_legacy_cycles(apps, schema_editor):
    # An old queued scan has no OSA authorization. Never replay it after upgrade.
    Cycle = apps.get_model("students", "GateCycle")
    Controller = apps.get_model("students", "GateController")
    ids = list(Cycle.objects.filter(phase="QUEUED").values_list("pk", flat=True))
    Controller.objects.filter(active_cycle_id__in=ids).update(active_cycle=None)
    Cycle.objects.filter(pk__in=ids).update(
        phase="CLOSED", outcome="CANCELLED", message="Workflow upgraded; scan again for OSA review.")


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_violation_evidence'),
    ]

    operations = [
        migrations.RunPython(cancel_unsent_legacy_cycles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aiinspection',
            name='confirmation_status',
            field=models.CharField(choices=[('CONFIRMED_ALLOW', 'Confirmed Violation - Allow Entry'), ('CONFIRMED_DENY', 'Confirmed Violation - Deny Entry'), ('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed Violation (Historical)'), ('REJECTED', 'False Detection')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='gatecycle',
            name='phase',
            field=models.CharField(default='WAITING_OSA', max_length=20),
        ),
    ]
