import { useId } from "react";
export function Icon({ name, className = "" }) { return <i className={`bi bi-${name} ${className}`} aria-hidden="true" />; }
export function StatusBadge({ children, icon = "info-circle", strong = false }) { return <span className={`status-badge ${strong ? "status-strong" : ""}`}><Icon name={icon} />{children}</span>; }
export function PageHeading({ title, description, children }) { return <div className="page-heading"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{children}</div>; }
export function EmptyState({ title = "No records found", message, icon = "inbox" }) { return <div className="empty-state"><Icon name={icon} /><h3>{title}</h3>{message && <p>{message}</p>}</div>; }
export function LoadingState({ message = "Loading records..." }) { return <div className="loading-state" role="status"><span className="spinner-border spinner-border-sm" aria-hidden="true" />{message}</div>; }
export function ErrorState({ error }) { return error ? <div className="alert sh-alert" role="alert"><Icon name="exclamation-circle" /> {error}</div> : null; }
export function SearchBar({ value, onChange, label = "Search", placeholder = "Search records?" }) { const id = useId(); return <div><label className="form-label" htmlFor={id}>{label}</label><div className="input-group"><span className="input-group-text"><Icon name="search" /></span><input id={id} type="search" className="form-control" placeholder={placeholder} value={value} onChange={event => onChange(event.target.value)} /></div></div>; }
export function Pagination({ page, pages, onChange, total }) { return <div className="pagination-bar"><span className="small text-muted">{total} records | Page {page} of {pages}</span><nav aria-label="Table pagination" className="btn-group"><button className="btn btn-outline-primary btn-sm" disabled={page <= 1} onClick={() => onChange(page - 1)}>Previous</button><button className="btn btn-outline-primary btn-sm" disabled={page >= pages} onClick={() => onChange(page + 1)}>Next</button></nav></div>; }
export function Detail({ label, children }) { return <div className="detail-item"><dt>{label}</dt><dd>{children ?? "Not available"}</dd></div>; }
