import { useState } from "react";
import useLiveData from "../hooks/useLiveData";
import { PageHeading,SearchBar,Pagination,ErrorState,EmptyState,LoadingState,StatusBadge,Icon } from "../components/UI";
export default function EmailNotifications() {
  const [search,setSearch] = useState(""); const [status,setStatus] = useState(""); const [page,setPage] = useState(1);
  const params = new URLSearchParams({q:search,status,page});
  const {data,error} = useLiveData(`http://127.0.0.1:8000/api/students/notifications/?${params}`);
  return <><PageHeading title="Email notifications" description="Delivery queue for recorded official offenses. Sending is handled by the existing email worker." /><ErrorState error={error} />
    <section className="card"><div className="card-body"><div className="row g-3 mb-4"><div className="col-md-8"><SearchBar label="Search notifications" value={search} onChange={value => {setSearch(value);setPage(1);}} placeholder="Student name or ID" /></div><div className="col-md-4"><label htmlFor="email-status-filter" className="form-label">Delivery status</label><select id="email-status-filter" className="form-select" value={status} onChange={event => {setStatus(event.target.value);setPage(1);}}><option value="">All delivery states</option>{["PENDING","SENDING","SENT","SKIPPED","FAILED"].map(value => <option key={value}>{value}</option>)}</select></div></div>
    {!data && !error ? <LoadingState /> : <><div className="table-responsive"><table className="table"><thead><tr><th>Student / Current email</th><th>Violation</th><th>Current minors</th><th>Major eq.</th><th>Queued (Manila)</th><th>Sent (Manila)</th><th>Delivery status</th></tr></thead><tbody>{data?.results.map(item => <tr key={item.id}><td><strong>{item.name}</strong><div className="small text-muted">{item.student_number}</div><div>{item.email || "No student email"}</div></td><td>{item.violation}</td><td>{item.total_minor_offenses}</td><td>{item.equivalent_major_offenses}</td><td>{new Date(item.created_at).toLocaleString("en-PH",{timeZone:"Asia/Manila"})}</td><td>{item.sent_at ? new Date(item.sent_at).toLocaleString("en-PH",{timeZone:"Asia/Manila"}) : "Not sent"}</td><td><StatusBadge icon={item.status === "SENT" ? "envelope-check" : "envelope"} strong={item.status === "FAILED"}>{item.status}</StatusBadge>{item.error && <p className="small text-muted mt-1 mb-0">{item.error}</p>}</td></tr>)}</tbody></table></div>{!data?.results.length && <EmptyState icon="envelope" title={error ? "Notifications unavailable" : "No matching email notices"} />}<Pagination page={data?.page || page} pages={data?.pages || 1} total={data?.total || 0} onChange={setPage} /></>}
    </div></section><div className="alert sh-alert mt-4"><Icon name="info-circle" /> SENT means the mail server accepted the message, not confirmed inbox delivery. Resending is not available in the current API; failed or uncertain deliveries require operator review.</div></>;
}
