import { useState } from "react";
import useLiveData from "../hooks/useLiveData";
import { PageHeading,SearchBar,Pagination,ErrorState,EmptyState,LoadingState,StatusBadge } from "../components/UI";
export default function ScanHistory() {
  const [search,setSearch] = useState(""); const [outcome,setOutcome] = useState(""); const [page,setPage] = useState(1);
  const params = new URLSearchParams({q:search,outcome,page});
  const {data,error} = useLiveData(`http://127.0.0.1:8000/api/students/audit/?${params}`);
  return <><PageHeading title="Entry & audit logs" description="Scan and review activity, including denied and incomplete attempts. This is not official offense history." /><ErrorState error={error} />
    <section className="card"><div className="card-body"><div className="row g-3 mb-4"><div className="col-md-8"><SearchBar label="Search audit logs" value={search} onChange={value => {setSearch(value);setPage(1);}} placeholder="Student name or ID" /></div><div className="col-md-4"><label htmlFor="audit-outcome" className="form-label">Passage outcome</label><select id="audit-outcome" className="form-select" value={outcome} onChange={event => {setOutcome(event.target.value);setPage(1);}}><option value="">All outcomes</option>{["ENTERED","DENIED","WALKED_AWAY","CANCELLED","UNCERTAIN","PENDING"].map(value => <option value={value} key={value}>{value.replaceAll("_"," ")}</option>)}</select></div></div>
    {!data && !error ? <LoadingState /> : <><div className="table-responsive"><table className="table"><thead><tr><th>Student</th><th>Scan (Manila)</th><th>AI result</th><th>OSA decision</th><th>Gate phase / Event</th><th>Entry result</th></tr></thead><tbody>{data?.results.map(item => <tr key={item.id}><td><strong>{item.name}</strong><div className="small text-muted">{item.student_number}</div></td><td>{new Date(item.scan_time).toLocaleString("en-PH",{timeZone:"Asia/Manila"})}</td><td>{item.ai_result || "Not received"}</td><td>{item.osa_decision?.replaceAll("_"," ") || "Not reviewed"}</td><td>{item.gate_phase?.replaceAll("_"," ") || "No gate cycle"}<div className="small text-muted">{item.gate_event || "No event recorded"}</div></td><td><StatusBadge icon={item.entered ? "door-open" : "person-standing"}>{item.outcome?.replaceAll("_"," ") || "Not recorded"}</StatusBadge><div className="small text-muted mt-1">Opening acknowledged: {item.gate_opened ? "Yes" : "No"}</div></td></tr>)}</tbody></table></div>{!data?.results.length && <EmptyState title={error ? "Audit data unavailable" : "No matching attempts"} />}<Pagination page={data?.page || page} pages={data?.pages || 1} total={data?.total || 0} onChange={setPage} /></>}
    </div></section></>;
}
