import useLiveData from "../hooks/useLiveData";
import { PageHeading,Detail,StatusBadge,ErrorState,Icon } from "../components/UI";
import { gateMessage } from "../hooks/useGateCycle";
export default function Settings() {
  const system = useLiveData("http://127.0.0.1:8000/api/students/system-status/");
  const camera = useLiveData("http://127.0.0.1:5000/camera-status");
  return <><PageHeading title="System settings & connections" description="Read-only operational information. Hardware and SMTP configuration remain in the existing services." /><ErrorState error={system.error} /><div className="row g-4">
    <div className="col-md-6"><section className="card h-100"><div className="card-body"><h2><Icon name="cloud-rain" /> Rainy Day Mode</h2><StatusBadge icon="slash-circle">Not implemented</StatusBadge><p className="small text-muted mt-3 mb-0">The AI has not been trained to identify slippers. There is no backend rainy-day policy, so no interactive switch is provided. OSA can review the captured evidence manually.</p></div></section></div>
    <div className="col-md-6"><section className="card h-100"><div className="card-body"><h2><Icon name="camera-video" /> Camera</h2><StatusBadge icon="camera">{camera.error ? "Service unavailable" : camera.data ? camera.data.active ? "Active" : "Idle" : "Checking"}</StatusBadge><p className="small text-muted mt-3 mb-0">The scanner starts the existing camera service after a valid ID scan. Camera selection is not exposed as an editable setting.</p></div></section></div>
    <div className="col-md-6"><section className="card h-100"><div className="card-body"><h2><Icon name="usb-symbol" /> Arduino Uno & gate</h2><StatusBadge icon="usb-symbol">{system.data ? system.data.arduino_connected ? "Connected" : "Offline" : "Unavailable"}</StatusBadge><p className="small mt-3">{system.data?.active_cycle ? gateMessage(system.data.active_cycle) : "No active cycle reported. Physical gate position is not independently measured."}</p><p className="small text-muted mb-0">The existing USB bridge uses the Uno protocol at 9600 baud. Serial-port selection and gate timing are managed outside this UI. No gate-control buttons are provided here.</p></div></section></div>
    <div className="col-md-6"><section className="card h-100"><div className="card-body"><h2><Icon name="person-walking" /> Entry sensing</h2><p className="small">The existing two HC-SR04 sensors identify an outside-to-inside passage.</p><dl className="detail-list"><Detail label="Reported cycle outcome">{system.data?.active_cycle?.outcome || "No active passage"}</Detail><Detail label="Latest cycle event">{system.data?.active_cycle?.message || "No active event"}</Detail></dl><p className="small text-muted mt-3 mb-0">Independent sensor readings, distance values and exit counts are not exposed. Opening the gate alone does not confirm entry.</p></div></section></div>
    <div className="col-md-6"><section className="card h-100"><div className="card-body"><h2><Icon name="envelope" /> SMTP notifications</h2><StatusBadge icon="envelope">{system.data ? system.data.smtp_configured ? "Credentials configured" : "Not configured" : "Unavailable"}</StatusBadge><p className="small text-muted mt-3 mb-0">Configuration comes from the existing environment. Credentials are never displayed here. A configured status does not verify delivery or worker availability. Test email and resend are not supported by the API.</p></div></section></div>
    <div className="col-md-6"><section className="card h-100"><div className="card-body"><h2><Icon name="journal-check" /> Official offense policy</h2><p className="small">Confirmed allow + acknowledged opening + sensor-confirmed entry. At most one official offense per student per local day.</p><dl className="detail-list"><Detail label="Configured timezone">{system.data?.timezone}</Detail><Detail label="Major equivalence">Every 3 total minors</Detail></dl><p className="small text-muted mt-3 mb-0">The backend applies these rules. They are not editable in this interface.</p></div></section></div>
  </div></>;
}
